NewRecordlinc/Controllers/FaqController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NewRecordlinc.App_Start;
using System.Data;
using DataAccessLayer.Common;
using DataAccessLayer.ColleaguesData;
namespace NewRecordlinc.Controllers
{
    public class FaqController : Controller
    {

        clsAdmin ObjAdmin = new clsAdmin();
        clsCommon ObjCommon = new clsCommon();
        //public ActionResult Index()
        //{
        //    if (SessionManagement.UserId != null && SessionManagement.UserId != "")
        //    {
        //        return RedirectToAction("Index", "Index");
        //    }
        //    else
        //    {
        //        return View();
        //    }
        //}

        //public ActionResult PrivacyPolicy()
        //{
        //    if (SessionManagement.UserId != null && SessionManagement.UserId != "")
        //    {
        //        return RedirectToAction("PrivacyPolicy", "Dashboard");
        //    }
        //    else if (SessionManagement.AdminUserId != null && SessionManagement.AdminUserId != "")
        //    {
        //        return RedirectToAction("PrivacyPolicy", "Dashboard");
        //    }

        //    else
        //    {
        //        DataTable dt = new DataTable();
        //        dt = ObjAdmin.GetAllCustomPageDetailsById(1);
        //        if (dt != null && dt.Rows.Count > 0)
        //        {
        //            ViewBag.PrivacyPolicy = ObjCommon.CheckNull(Convert.ToString(dt.Rows[0]["PageDesc"]), string.Empty);
        //        }
        //        return PartialView("_PrivacyPolicy");
        //    }
        //}

        public ActionResult Index()
        {
            if (SessionManagement.UserId != null && SessionManagement.UserId != "")
            {
                return RedirectToAction("Index", "Index");
            }
            else
            {
                return View("FAQ");
            }
        }


        public ActionResult PrivacyPolicy()
        {
            if (SessionManagement.UserId != null && SessionManagement.UserId != "")
            {
                return RedirectToAction("PrivacyPolicy", "Dashboard");
            }
            else if (SessionManagement.AdminUserId != null && SessionManagement.AdminUserId != "")
            {
                return RedirectToAction("PrivacyPolicy", "Dashboard");
            }

            else
            {
                return View();
            }
        }



        //public ActionResult Termsconditions()
        //{
        //    if (SessionManagement.UserId != null && SessionManagement.UserId != "")
        //    {
        //        return RedirectToAction("Index", "Index");
        //    }
        //    else
        //    {
        //        DataTable dt = new DataTable();
        //        dt = ObjAdmin.GetAllCustomPageDetailsById(2);
        //        if (dt != null && dt.Rows.Count > 0)
        //        {
        //            ViewBag.TermsAndConditions = ObjCommon.CheckNull(Convert.ToString(dt.Rows[0]["PageDesc"]), string.Empty);
        //        }
        //        return PartialView("_Termsconditions");
        //    }
        //}

        //public ActionResult HIPAA()
        //{
        //    if (SessionManagement.UserId != null && SessionManagement.UserId != "")
        //    {
        //        return RedirectToAction("Index", "Index");
        //    }
        //    else
        //    {
        //        return PartialView("_HIPAA");
        //    }
        //}
        
        //RM-414
        public ActionResult HIPAA()
        {
            return View();
        }

        //public ActionResult SiteMap()
        //{
        //    //-- 6211 - Commented session checking code becuse causing problem when redirected from public profile.
        //    //if (SessionManagement.UserId != null && SessionManagement.UserId != "")
        //    //{
        //    //    return RedirectToAction("Index", "Index");
        //    //}
        //    //else
        //    //{
        //    return PartialView("_SiteMap");
        //    //}
        //}

        //RM-414 Static page for Sitemap
        public ActionResult SiteMap()
        {
            return View();
        }

        public ActionResult TermsAndConditions()
        {
            return View();
        }

        public ActionResult HelpAndTraining()
        {
            return View();
        }

    }
}

NewRecordlinc/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NewRecordlinc.Models.User;
using NewRecordlinc.App_Start;
using DataAccessLayer.Common;
using DataAccessLayer.ColleaguesData;
using System.Configuration;
using System.Data;
using System.Web.Helpers;
using DataAccessLayer.FlipTop;
using System.Web.Script.Serialization;
using BO.Models;
using BusinessLogicLayer;
using BO.ViewModel;
using BO.Constatnt;
namespace NewRecordlinc.Controllers
{
    public class UserController : Controller
    {
        mdlForgotPassword MdlForgotPassword = null;
        clsCompany ObjCompany = new clsCompany();
        clsCommon objCommon = new clsCommon();
        clsTemplate ObjTemplate = new clsTemplate();
        clsColleaguesData ObjColleaguesData = new clsColleaguesData();
        clsAdmin ObjAdmin = new clsAdmin();
        TripleDESCryptoHelper ObjTripleDESCryptoHelper = new TripleDESCryptoHelper();
        CommonBLL objcommonBll = new CommonBLL();

        public ActionResult Index(string UserName = null, string Password = null, string PatId = null,string Status = null,string IsFrom = null)
        {
            TempData.Keep("PMSReferralError");
            TempData.Keep("PMSConfigError");
            string[] SplitCredential = null; string messageid = string.Empty; string Messagetypeid = string.Empty;
            if (Request["DTPMKC"] != null && Request["DTPMKC"] != "")
            {
                string CheckSPace = Request["DTPMKC"].ToString().Replace(" ", "+");
                string DecryptString = ObjTripleDESCryptoHelper.decryptText(CheckSPace);
                SplitCredential = DecryptString.Split(new string[] { "||" }, StringSplitOptions.None);
                UserName = SplitCredential[0];
                Password = SplitCredential[1];
                messageid = SplitCredential[2];
                Messagetypeid = SplitCredential[2];
            }
            if (TempData["EncriptedString"] != null)
            {
                ViewBag.EncriptesString = TempData["EncriptedString"].ToString();
            }
            TempData["IsFrom"] = false;
            if(IsFrom == BO.Constatnt.Common.IsFrom)
            {
                Session["iLuvDentistImage"] = "~/Content/images/ilogo.png";
                TempData["IsFrom"] = true;
            }
            //if (Request.QueryString["p"] != null)
            //{
            //    if (!string.IsNullOrWhiteSpace(Request.QueryString["p"]))
            //    {
            //        ObjTripleDESCryptoHelper = new TripleDESCryptoHelper();
            //        string CheckSPace = Request.QueryString["p"].ToString().Replace(' ', '+');
            //        string DecryptString = ObjTripleDESCryptoHelper.decryptText(CheckSPace);
            //        SplitCredential = DecryptString.Split(new string[] { "||" }, StringSplitOptions.None);
            //        UserName = SplitCredential[0];
            //        Password = SplitCredential[1];
            //        messageid = SplitCredential[2];
            //        Messagetypeid = SplitCredential[2];
            //    }
            //}
            ObjCompany.GetActiveCompany();
            if (SessionManagement.UserId != null && SessionManagement.UserId != "")
            {
                DataTable dtCheckFirst = new DataTable();

                dtCheckFirst = ObjColleaguesData.GetFirstLoginCount(Convert.ToInt32(SessionManagement.UserId));
                if (dtCheckFirst.Rows.Count == 0)
                {
                    bool Result = false;
                    Result = objCommon.InsertLogedInfo(Convert.ToInt32(SessionManagement.UserId));
                    return RedirectToAction("Index", "Index", new { newuser = Convert.ToInt32(SessionManagement.UserId) });
                }
                else
                {

                    if (SplitCredential != null)
                    {

                        return RedirectToAction("Index", "Inbox", new { messageid = messageid, mtypeid = Messagetypeid });
                    }
                    return RedirectToAction("Index", "Index");
                }

            }
            else if (!string.IsNullOrEmpty(UserName))
            {
                if (!string.IsNullOrEmpty(Password))
                {
                    Password = Password.Replace(" ", "+");
                    DataTable dtLogin = new DataTable();
                    DataTable dtFirstLogin = new DataTable();
                    DataTable dtCheckFirst = new DataTable();
                    int valid = 0;
                    DataTable dtCheck = ObjColleaguesData.CheckEmailInSystem(UserName);
                    if (dtCheck != null && dtCheck.Rows.Count > 0)
                    {
                        int IsInSystem = Convert.ToInt32(dtCheck.Rows[0]["IsInSystem"]);
                        if (IsInSystem == 1)
                        {
                            TripleDESCryptoHelper cryptoHelper = new TripleDESCryptoHelper();
                            //RM-283 Password is passed instead of encryptedPassword
                            string encryptedPassword = cryptoHelper.encryptText(Password);
                            string decryptedPatId = cryptoHelper.decryptText(PatId);
                            int PatientID = Convert.ToInt32(decryptedPatId);
                            dtLogin = ObjColleaguesData.LoginUserBasedOnUsernameandPassword(UserName,encryptedPassword);
                            #region Login As Doctor
                            if (dtLogin != null && dtLogin.Rows.Count > 0)
                            {
                                valid = Convert.ToInt32(dtLogin.Rows[0]["UserId"]);
                                SessionManagement.UserId = objCommon.CheckNull(Convert.ToString(dtLogin.Rows[0]["UserId"]), string.Empty);
                                SessionManagement.ParentUserId = (!string.IsNullOrEmpty(Convert.ToString(dtLogin.Rows[0]["ParentUserId"])) ? Convert.ToString(dtLogin.Rows[0]["ParentUserId"]) : Convert.ToString(Session["UserId"]));
                                SessionManagement.LocationId = objCommon.CheckNull(Convert.ToString(dtLogin.Rows[0]["LocationId"]), string.Empty);
                                SessionManagement.FirstName = objCommon.CheckNull(Convert.ToString(dtLogin.Rows[0]["FirstName"]), string.Empty);
                                SessionManagement.UserPaymentVerified = PaymentBLL.CheckUserPayment(Convert.ToInt32(SessionManagement.UserId));
                                SessionManagement.GetMemberPlanDetails = objcommonBll.GetUserPlanDetails(Convert.ToInt32(dtLogin.Rows[0]["UserId"]));
                                string ImageName = "";
                                ImageName = objCommon.CheckNull(Convert.ToString(dtLogin.Rows[0]["ImageName"]), string.Empty);
                                if (string.IsNullOrEmpty(ImageName))
                                {
                                    if (!System.IO.File.Exists(ImageName))
                                    {
                                        SessionManagement.DoctorImage = objCommon.CheckNull(Convert.ToString(ConfigurationManager.AppSettings["DefaultDoctorImage"]), string.Empty);
                                    }
                                    else
                                    {
                                        SessionManagement.DoctorImage = objCommon.CheckNull(Convert.ToString(ConfigurationManager.AppSettings["DoctorImage"]), string.Empty) + ImageName;
                                    }
                                }
                                else
                                {
                                    SessionManagement.DoctorImage = objCommon.CheckNull(Convert.ToString(ConfigurationManager.AppSettings["DoctorImage"]), string.Empty) + ImageName;
                                }
                                Session["DoctorImage"] = SessionManagement.DoctorImage;


                                if (!string.IsNullOrEmpty(Status))
                                {
                                    if (Status == "2")
                                    {
                                        bool result = ObjAdmin.UpdateUserStatus(Convert.ToInt32(dtLogin.Rows[0]["UserId"]), 1); // When user comes from link of DeActive 
                                    }

                                }


                                dtCheckFirst = ObjColleaguesData.GetFirstLoginCount(Convert.ToInt32(dtCheck.Rows[0]["UserId"]));
                                if (dtCheckFirst.Rows.Count == 0)
                                {
                                    bool Result = false;
                                    Result = objCommon.InsertLogedInfo(Convert.ToInt32(SessionManagement.UserId));
                                    //return RedirectToAction("Index", "Index", new { newuser = Convert.ToInt32(dtCheck.Rows[0]["UserId"]) });
                                    //RM-117 Redirection to dashboard while clicking on the Team member mail first time. 
                                    return RedirectToAction("Index", "Index");

                                }
                                else
                                {
                                    bool Result = false;
                                    Result = objCommon.InsertLogedInfo(Convert.ToInt32(SessionManagement.UserId));
                                    if (SplitCredential != null)
                                    {

                                        messageid = SplitCredential[2];
                                        Messagetypeid = SplitCredential[3];
                                        return RedirectToAction("Index", "Inbox", new { messageid = messageid, mtypeid = Messagetypeid });
                                    }
                                    return RedirectToAction("Index", "Index",new {PId = PatientID });

NewRecordlinc/Views/Faq/HIPAA.cshtml


@{
    ViewBag.Title = "Recordlinc - Privacy Policy";
    Layout = "~/Views/Shared/NewSiteLayout.cshtml";
}

<main id="main">
    <div class="page_haading_holder">
        <div class="container navigation_container">
            <div class="row navigation_row">
                <div class="col-xs-12">
                    <div class="page_heading">
                        <h1>HIPAA</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="investment-packages-main-bg about-us">
        <div class="block-investment-table plane_pricing_table hippa">
            <div class="container">
                <div class="row ">
                    <div class="col-xs-12">
                        <img class="img-responsive" src="~/Content/css/HomePage/images/new/hippa_banner.jpg" alt="" />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="block-facilities team-wrap-bg careers clearfix policy">
                            <div class="col-xs-12">

                                <p>The HIPAA Security Rule identifies standards and implementation specifications that organizations must meet in order to become compliant. All organizations, including Dental Practices, which access, store, maintain or transmit patient-identifiable information, such as dental x-rays or photographic images, are required by law to meet the HIPAA Security Standards by April 21, 2005.</p>
                                <p>The general requirements of the HIPAA Security Rule establish that covered entities must do the following:</p>
                                <div class="block-facilities">
                                    <ul class="list-holder list-unstyled">
                                        <li><span class="circle"><i class="icon-chevron-small-right"></i></span>Ensure the confidentiality, integrity, and availability of all electronic protected health information(ePHI) the covered entity creates, receives, maintains, or transmits.</li>
                                        <li><span class="circle"><i class="icon-chevron-small-right"></i></span>Protect against any reasonably anticipated threats or hazards to the security or integrity of such information.</li>
                                        <li><span class="circle"><i class="icon-chevron-small-right"></i></span>Protect against any reasonably anticipated uses or disclosures of such information that are not permitted or required.</li>
                                        <li><span class="circle"><i class="icon-chevron-small-right"></i></span>Ensure compliance by the workforce.</li>
                                        <li><span class="circle"><i class="icon-chevron-small-right"></i></span>Protect against any reasonably anticipated uses or disclosures of such information that are not permitted or required.</li>
                                    </ul>
                                </div>
                                <p>Covered entities have been provided flexibility of approach. This implies that covered entities may use any security measures that allow the covered entity to reasonably and appropriately implement the standards and implementation specifications.</p>
                                <p>RecordLinc Inc. takes HIPAA regulations, patient privacy and security of its data seriously. We have put into practice a series of security measures and procedures that exceeds the standard requirements. RecordLinc Inc. will continually seek to improve systems and internal practice and policies to ensure the highest level of integrity and security across all systems. This will include but not be limited to: </p>
                                <div class="block-facilities">
                                    <ul class="list-holder list-unstyled">
                                        <li><span class="circle"><i class="icon-chevron-small-right"></i></span>A 128-bit SSL connection</li>
                                        <li><span class="circle"><i class="icon-chevron-small-right"></i></span>Automatic timeout features</li>
                                        <li><span class="circle"><i class="icon-chevron-small-right"></i></span>Unique user names with password protection</li>
                                        <li><span class="circle"><i class="icon-chevron-small-right"></i></span>Data Encryption</li>
                                        <li><span class="circle"><i class="icon-chevron-small-right"></i></span>Storage where data is backed up multiple times</li>
                                        <li><span class="circle"><i class="icon-chevron-small-right"></i></span>Extensive user audit trails</li>
                                        <li><span class="circle"><i class="icon-chevron-small-right"></i></span>Data is stored indefinitely</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="investment-packages-main-bg about-us">

        <div class="block-investment-table pro">
            <div class="container">

                <div class="row">
                    <div class="col-md-12">
                        <div class="col-md-6">
                            <a  href='@Url.Action("Index", "FreeToPaid")' target="_blank">
                                <img class="img-responsive" src="~/Content/css/HomePage/images/new/pro.jpg" alt="" />
                            </a>
                        </div>
                        <div class="col-md-6">
                            <a href="@Url.Action("SearchResult", "Profiles")">
                                <img class="img-responsive" src="~/Content/css/HomePage/images/new/professionals.jpg" alt="" />
                        </a>
                       </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="block-links">
        <div class="container">
            <div class="col">
                <a href="@Url.Action("News", "Aboutus")">
                    <i class="icon"><img src="~/Content/css/HomePage/images/new/img43.png" alt="image description"></i>
                    <span class="text">News</span>
                </a>
            </div>
            <div class="col">
                <a href="@Url.Action("HIPAA", "Faq")">
                    <i class="icon"><img src="~/Content/css/HomePage/images/new/img43.png" alt="image description"></i>
                    <span class="text">HIPAA <br>Compliance</span>
                </a>
            </div>
            <div class="col">
                <a href="@Url.Action("Index", "Faq")">
                    <i class="icon"><img src="~/Content/css/HomePage/images/new/img43.png" alt="image description"></i>
                    <span class="text">FAQ</span>
                </a>
            </div>
            <div class="col">
                <a href="@Url.Action("Index", "Quicktour")">
                    <i class="icon"><img src="~/Content/css/HomePage/images/new/img43.png" alt="image description"></i>
                    <span class="text">Demo</span>
                </a>
            </div>
        </div>
    </div>
</main>

NewRecordlinc/Views/Faq/SiteMap.cshtml
@{
    ViewBag.Title = "Recordlinc - SiteMap";
    Layout = "~/Views/Shared/NewSiteLayout.cshtml";
}

<script type="text/javascript">
    function SearchbyLocation() {

        var city = "";
        var state = "";
        var country = "";
        window.location.href = '@Url.Action("SearchResult", "Profiles")';  //?city=' + city + '&state=' + state + '&country=' + country;
    }

    function SearchDatabase() {
            var fname = "";
            var lname = "";
            window.location.href = '@Url.Action("SearchResult", "Profiles")';
        }

</script>

<main id="main">
    <div class="page_haading_holder">
        <div class="container navigation_container">
            <div class="row navigation_row">
                <div class="col-xs-12">
                    <div class="page_heading">
                        <h1>Site Map</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="investment-packages-main-bg about-us">

        <div class="block-investment-table plane_pricing_table">
            <div class="container">

                <div class="row">
                    <div class="col-md-12">
                        <div class="block-facilities careers sitemap">
                            <ul class="list-holder list-unstyled">
                                <li><a  href='@Url.Action("Index", "User")'><span class="circle"><i class="icon-chevron-small-right"></i></span>Home</a></li>
                                <li><a href='@Url.Action("HIPAA", "Faq")'><span class="circle"><i class="icon-chevron-small-right"></i></span>HIPAA Compliance</a></li>
                                <li><a href='@Url.Action("Index", "ContactUs")'><span class="circle"><i class="icon-chevron-small-right"></i></span>Contact Us</a></li>
                                <li><a href='@Url.Action("Index", "Quicktour")'><span class="circle"><i class="icon-chevron-small-right"></i></span>Quick Tour</a></li>
                                <li><a href='@Url.Action("TermsAndConditions", "Faq")'><span class="circle"><i class="icon-chevron-small-right"></i></span>Terms of Use</a></li>
                                <li><a href="javascript:;" onclick="SearchDatabase()"><span class="circle"><i class="icon-chevron-small-right"></i></span>Search by Doctor Name</a></li>
                                <li><a href='@Url.Action("Index", "PlanAndPricing")'><span class="circle"><i class="icon-chevron-small-right"></i></span>Plan & Pricing</a></li>
                                <li><a href='@Url.Action("PrivacyPolicy", "Faq")'><span class="circle"><i class="icon-chevron-small-right"></i></span>Privacy Policy</a></li>
                                <li><a href="javascript:;" onclick="SearchbyLocation()"><span class="circle"><i class="icon-chevron-small-right"></i></span>Search by Location</a></li>
                                <li><a href='@Url.Action("Index", "Faq")'><span class="circle"><i class="icon-chevron-small-right"></i></span>FAQ</a></li>
                                <li>
                                    <a href='@Url.Action("Index", "Aboutus")'><span class="circle"><i class="icon-chevron-small-right"></i></span>About Us</a>
                                    <ul>
                                        <li><a href='@Url.Action("Team", "Aboutus")'>Team</a></li>
                                        <li><a href='@Url.Action("Career", "Aboutus")'>Careers</a></li>
                                        <li><a href='@Url.Action("News", "Aboutus")'>News</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <div class="block-links">
        <div class="container">
            <div class="col">
                <a href="@Url.Action("News", "Aboutus")">
                    <i class="icon"><img src="~/Content/css/HomePage/images/new/img43.png" alt="image description"></i>
                    <span class="text">News</span>
                </a>
            </div>
            <div class="col">
                <a href="@Url.Action("HIPAA", "Faq")">
                    <i class="icon"><img src="~/Content/css/HomePage/images/new/img43.png" alt="image description"></i>
                    <span class="text">HIPAA <br>Compliance</span>
                </a>
            </div>
            <div class="col">
                <a href="@Url.Action("Index", "Faq")">
                    <i class="icon"><img src="~/Content/css/HomePage/images/new/img43.png" alt="image description"></i>
                    <span class="text">FAQ</span>
                </a>
            </div>
            <div class="col">
                <a href="@Url.Action("Index", "Quicktour")">
                    <i class="icon"><img src="~/Content/css/HomePage/images/new/img43.png" alt="image description"></i>
                    <span class="text">Demo</span>
                </a>
            </div>
        </div>
    </div>
</main>

NewRecordlinc/Views/Faq/_Sitemap.cshtml
@{
    ViewBag.Title = "Recordlinc - SiteMap";
    Layout = "~/Views/Shared/SiteLayout.cshtml";
}
<script type="text/javascript">
    function SearchbyLocation() {

        var city = "";
        var state = "";
        var country = "";
        window.location.href = '@Url.Action("SearchResult", "Profiles")';  //?city=' + city + '&state=' + state + '&country=' + country;
    }

</script>
<!-- InnerPage starts here -->
<section id="inner">
	<div class="container" style="text-align:justify;">    	
        
        <div class="content sitemap">
        	<h2 class="title">SiteMap</h2>
            <ul class="even">
            	<li>
                	<ul class="listicons">
                        <li><a href='@Url.Action("Index", "User")'>Home</a></li>
                        <li><a  href='@Url.Action("Index", "Quicktour")'>Quick Tour</a></li>
                        <li><a href='@Url.Action("Index", "PlanAndPricing")'>Plan &amp; Pricing</a></li>
                        <li><a  href='@Url.Action("Index", "Faq")'>FAQ</a></li>
                        <li><a href='@Url.Action("HIPAA", "Faq")'>HIPAA Compliance</a></li>                         
                        <li><a href='@Url.Action("Termsconditions", "Faq")'>Terms of Use</a></li>
                        <li><a href='@Url.Action("PrivacyPolicy", "Faq")'>Privacy Policy</a></li>
                    </ul>
                </li>
                <li>
                	<ul class="listicons">
                        <li><a href='@Url.Action("Index", "Aboutus")'>About Us</a>
                        	<ul class="sublisticons">
                                <li><a href='@Url.Action("Team", "Aboutus")'>Team</a></li>  
                                <li><a href='@Url.Action("Career", "Aboutus")'>Careers</a></li>
                                <li><a href='@Url.Action("News", "Aboutus")'>News</a></li>      
                                <li style="display:none;"><a href="#">Dentrix & Recordlinc</a></li>                                       
                            </ul>
                        </li> 
                        <li><a href='@Url.Action("Index", "ContactUs")'>Contact Us</a></li>                        
                        <li><a href="Javascript:;" onclick="SearchDatabase()">Search by Doctor Name</a></li> 
                        <li><a href="Javascript:;" onclick="SearchbyLocation()">Search by Location</a></li> 
                    </ul>
                </li>
            </ul>
            
        </div>
        
        <div class="aside">
   			<a class="advert" href="Javascript:;" onclick="SearchDatabase()"><img class="inline" src="../Images/inner/search-database.jpg" alt="Grow your practice by expanding your professional network"></a>
        </div>
        
        <div class="clear"></div>
  </div>
</section>
<!-- InnerPage starts ends here -->