NewRecordlinc/Controllers/LandingController.cs
using BO.Models;
using BusinessLogicLayer;
using DataAccessLayer.ColleaguesData;
using DataAccessLayer.Common;
using DataAccessLayer.FlipTop;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace NewRecordlinc.Controllers
{
    public class LandingController : Controller
    {
        clsTemplate ObjTemplate = new clsTemplate();
        clsColleaguesData ObjColleaguesData = new clsColleaguesData();
        clsCommon objCommon = new clsCommon();
        TripleDESCryptoHelper ObjTripleDESCryptoHelper = new TripleDESCryptoHelper();
        clsAdmin objAdmin = new clsAdmin();

        // GET: Landing
        [ActionName("A-Dentists-Guide-to-Referrals")]        
        public ActionResult Index()
        {
            return View("Index");
        }        

        [ActionName("Referral-Machine-for-Dentists")]
        public ActionResult LandingPage2()
        {
            return View("LandingPage2");
        }

        [ActionName("dos-and-donts-for-online-dentist-reviews")]
        public ActionResult LandingPage3()
        {
            return View("LandingPage3");
        }

        [ActionName("Referral-Autopilot-for-dentist")]
        public ActionResult LandingPage4()
        {
            return View("LandingPage4");
        }

        [HttpPost]
        public ActionResult SendLandingEmail(string emailId, string pdfType)
        {
            object obj = string.Empty;
            string emailAddress = Convert.ToString(emailId);
            string PdfTypeLink = string.Empty;
            string strPdfType = string.Empty;
            string strPageLink = string.Empty;
            if (pdfType == Convert.ToString((int)BO.Enums.Common.Landing.DentistsGuideToReferrals))
            {
                strPdfType = "A-Dentists-Guide-to-Referrals";
                strPageLink = Convert.ToString(ConfigurationManager.AppSettings["Lanpag1"]);
                PdfTypeLink = Convert.ToString(ConfigurationManager.AppSettings["pdf1"]);
            }
            if (pdfType == Convert.ToString((int)BO.Enums.Common.Landing.DosAndDontsForDentists))
            {
                strPdfType = "dos-and-donts-for-online-dentist-reviews";
                strPageLink = Convert.ToString(ConfigurationManager.AppSettings["Lanpag2"]);
                PdfTypeLink = Convert.ToString(ConfigurationManager.AppSettings["pdf2"]);
            }
            if (pdfType == Convert.ToString((int)BO.Enums.Common.Landing.ReferralAutopilotforDentist))
            {
                strPdfType = "Referral-Autopilot-for-dentist";
                strPageLink = Convert.ToString(ConfigurationManager.AppSettings["Lanpag3"]);
                PdfTypeLink = Convert.ToString(ConfigurationManager.AppSettings["pdf3"]);
            }
            if (pdfType == Convert.ToString((int)BO.Enums.Common.Landing.ReferralMachineForDentists))
            {
                strPdfType = "Referral-Machine-for-Dentists";
                strPageLink = Convert.ToString(ConfigurationManager.AppSettings["Lanpag4"]);
                PdfTypeLink = Convert.ToString(ConfigurationManager.AppSettings["pdf4"]);
            }

            clsTemplate objclsTemplate = new clsTemplate();
            
            //send email to user for download the pdf.
            var IsMailSent = objclsTemplate.SendLandingEmailToUser(emailAddress, PdfTypeLink, strPdfType);            

            //store user information in the database.
            LandingBLL objLandingBLL = new LandingBLL();
            LandingHistory objLandingHistory = new LandingHistory();
            objLandingHistory.Email = emailAddress;
            objLandingHistory.LandingPageName = strPageLink;
            var IsResult = objLandingBLL.InsertLandingHistory(objLandingHistory);            
            if (IsMailSent || IsResult)
            {
                obj = "1";                
            }            
            return Json(obj, JsonRequestBehavior.AllowGet);
        }        


        public ActionResult ContactUs(string FullName, string Email, string Message, string CurrentUrl)
        {                       
            try
            {
                object obj = string.Empty;
                clsTemplate objclsTemplate = new clsTemplate();
                string UserMail = Email;
                var strCurrentUrl = CurrentUrl.Split('/');
                string pageUrl = Convert.ToString(strCurrentUrl[3]);                
                string SalesEmail = Convert.ToString(ConfigurationManager.AppSettings.Get("SaleEmail"));
                var IsMailSent = objclsTemplate.SendEmailToSalesFromLanding(UserMail, SalesEmail, FullName, Message, pageUrl);
                if (IsMailSent)
                {
                    obj = "1";                   
                }
                return Json(obj, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(ex.ToString(), JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult SignupFromLanding(string email)
        {
            try
            {
                object obj = string.Empty;

                //Call Socialmedia API            
                CommonBLL objCommonBLL = new CommonBLL();
                Person person = objCommonBLL.GetSocialMediaPerson(email);
                DataTable dtCheckEmail = new DataTable();
                dtCheckEmail = ObjColleaguesData.CheckEmailInSystem(email);


                if (dtCheckEmail.Rows.Count > 0)
                {
                    // send template for forgot password

                    DataTable dtCheck = ObjColleaguesData.CheckEmailExistsAsDoctor(email);
                    if (dtCheck != null && dtCheck.Rows.Count > 0)
                    {
                        string FullName = string.Empty; string EncPassword = string.Empty;
                        int AllowLogin = Convert.ToInt32(dtCheckEmail.Rows[0]["Status"]);
                        if (AllowLogin == 1)
                        {
                            #region Send Password to user if already in system
                            // send password tempalte
                            FullName = objCommon.CheckNull(Convert.ToString(dtCheck.Rows[0]["FirstName"]), string.Empty) + " " + objCommon.CheckNull(Convert.ToString(dtCheck.Rows[0]["LastName"]), string.Empty);
                            EncPassword = objCommon.CheckNull(Convert.ToString(dtCheckEmail.Rows[0]["Password"]), string.Empty);
                            ObjTemplate.SendingForgetPassword(FullName, email, EncPassword);
                            #endregion
                            obj = "4";
                        }
                        else
                        {
                            if (AllowLogin == 2)//If Email is De Active by Admin then send this link as below
                            {
                                string companywebsite = "";
                                if (Session["CompanyWebsite"] != null)
                                {
                                    companywebsite = Session["CompanyWebsite"].ToString();
                                    //companywebsite = "http://localhost:2298/";
                                }
                                FullName = objCommon.CheckNull(Convert.ToString(dtCheck.Rows[0]["FirstName"]), string.Empty) + " " + objCommon.CheckNull(Convert.ToString(dtCheck.Rows[0]["LastName"]), string.Empty);
                                EncPassword = objCommon.CheckNull(Convert.ToString(dtCheck.Rows[0]["Password"]), string.Empty);
                                ObjTemplate.NewUserEmailFormat(email, companywebsite + "/User/Index?UserName=" + email + "&Password=" + EncPassword + "&Status=2", ObjTripleDESCryptoHelper.decryptText(EncPassword), companywebsite);
                                obj = "3";
                            }
                        }

                    }
                    else
                    {
                        #region Re Send sign up tempalte to user of temp table
                        DataTable dttemp = new DataTable();
                        string EncPassword = string.Empty;
                        string companywebsite = "";
                        if (Session["CompanyWebsite"] != null)
                        {
                            companywebsite = Session["CompanyWebsite"].ToString();
                        }
                        dttemp = objAdmin.GetTempSignupByEmail(email);
                        if (dttemp.Rows.Count > 0)
                        {
                            EncPassword = objCommon.CheckNull(Convert.ToString(dttemp.Rows[0]["password"]), string.Empty);
                            ObjTemplate.NewUserEmailFormat(email, companywebsite + "/User/Index?UserName=" + email + "&Password=" + EncPassword, ObjTripleDESCryptoHelper.decryptText(EncPassword), companywebsite); // send tempate to admin if doctor sing up in system
                            obj = "2";
                        }                       
                        #endregion

                    }

                }
                else
                {
                    #region Doctor sign up in system
                    string Password = objCommon.CreateRandomPassword(8);
                    string EncPassword = ObjTripleDESCryptoHelper.encryptText(Password);
                    string Accountkey = Crypto.SHA1(Convert.ToString(DateTime.Now.Ticks));
                    //Doctor sign up                    

                    string fullName = person.FullName;

NewRecordlinc/Views/Landing/Index.cshtml

@{
    ViewBag.Title = "A-Dentists-Guide-to-Referrals";
    Layout = "~/Views/Landing/_LandingLayout.cshtml";
}

@*<h2>Index</h2>*@
<link href="~/Content/Landing/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
<link href="~/Content/Landing/css/jquery-ui.min.css" rel="stylesheet" type="text/css" />
<link href="~/Content/Landing/css/style.css" rel="stylesheet" type="text/css" />
<link href="~/Content/Landing/css/responsive.css" rel="stylesheet" type="text/css" />
<style>
    .submitone{
        font-family: 'WorkSansRegular';
        font-size: 18px;
        color: #fff;
        background-color: #0e274d;
        border: 0px;
        border-radius: 3px;
        margin-top: 25px;
        padding: 13px 15px;
    }    
</style>
<section class="banner">
    <div class="col-sm-3 banner_left">
        <div class="email_download">
            <h1>11 Tips for Increasing Referrals</h1>
            @*<form action="@Url.Action("SendLandingEmail", "Landing")" method="post" id="Landing1">*@
            <form>
                <label>Email*</label>                
                <input type="email" id="txtemail" placeholder="Enter your e-mail to download" class="input_text">
                <div id="dvWarnMsg" style="display:none;color:red;font-size:16px;"><b>Please enter valid email id!</b></div>
                <a href="javascript:;" class="banner_btn" onclick="checkEmail()" @*data-toggle="modal"*@ @*data-target="#myModal"*@>Download Now</a>
            </form>
        </div>
    </div>
    <div class="col-sm-9 banner_right">
        <div class="dentist_guide">
            <div class="title">
                <h2>A Dentist’s Guide to Getting a Regular Flow of Referrals</h2>
            </div>
            <p>Achieving a high rate of referrals is key to building a successful dental practice. Not only do they increase profits, but they are also generally one of the best kind of patients.</p>
            <p>Referrals already have a positive attitude to your practice and require little encouragement to become a pa-tient. Typically, they also know what they want and what their goals are. These two factors reduce the need for a time-consuming sales pitch and allow you to get on with the treatment.</p>
            <img src="~/Content/Landing/images/banner_person.png" class="img-responsive" alt="RecordLinc Logo" />
        </div>
    </div>
</section>
<section class="mistakes">
    <div class="col-sm-7 mistake_right">
        <div class="common">
            <div class="title">
                <h2>Common Mistakes</h2>
            </div>
            <div class="mistakes_accordion">
                <h3>A Failure to Engage With Referrals</h3>
                <div class="mistake_content">
                    <p>
                        Once presented with a referral, however, it should not be perceived as a ‘done deal’. Too many dentists fail to take advantage of these
                        opportunities by neglecting to engage properly with referrals. It is vital to ask the right questions and listen carefully to a referrals needs. You should ask the potential patient what it was they liked the current patient said about you. Establish what a referral most values in a dentist and a practice. Do they want a sympathetic
                        dentist who will guide them step by step through treatment? Or do they prefer a no fuss ‘’in and out’’ approach?

                    <p>After identifying a referral’s needs, be sure to deliver exactly what they want.</p>
                </div>
                <h3>Too Few Resources Dedicated to Getting Referrals</h3>
                <div class="mistake_content">
                    <p>
                        Once presented with a referral, however, it should not be perceived as a ‘done deal’. Too many dentists fail to take advantage of these
                        opportunities by neglecting to engage properly with referrals. It is vital to ask the right questions and listen carefully to a referrals needs. You should ask the potential patient what it was they liked the current patient said about you. Establish what a referral most values in a dentist and a practice. Do they want a sympathetic
                        dentist who will guide them step by step through treatment? Or do they prefer a no fuss ‘’in and out’’ approach?

                    <p>After identifying a referral’s needs, be sure to deliver exactly what they want.</p>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-5 mistake_left">
        <div class="conceptions">
            <div class="title">
                <h2>Misconceptions</h2>
            </div>
            <p>There are three common mistakes dentists' make regarding referrals:</p>
            <ul>
                <li>Only long-time patients refer.</li>
                <li>Patients only refer after receiving fantastic treatment.</li>
                <li>Patients will only refer once.</li>
            </ul>
        </div>
    </div>
</section>
<section class="tips">
    <div class="container">
        <div class="row">
            <div class="col-sm-5">
                <div class="title">
                    <h2>11 Tips <br>for Increasing Referrals</h2>
                </div>
                <img src="~/Content/Landing/images/tips.png" class="img-responsive" alt="Travis Tips" />
                <a href="/Signup">Sign Up Today</a>
            </div>
            <div class="col-sm-7">
                <ol>
                    <li>Ensure Your Office is Fit to be Referred</li>
                    <li>Tell Patients You Want Their Referrals</li>
                    <li>Publicize Your Referral Program Throughout Your Practice</li>
                    <li>Publish a Regular Newsletter</li>
                    <li>Hold Referral Contests for Staff and Patients</li>
                    <li>Give Gifts to Existing Patients</li>
                    <li>Welcome New Patients With a Gift</li>
                    <li>Organize Regular Patient Appreciation Events</li>
                    <li>Leverage Patient's Influence Outside of the Dental Practice</li>
                    <li>Turn New Callers Into New Patients</li>
                    <li>Sign up for RecordLinc</li>
                </ol>
            </div>
        </div>
    </div>
</section>
<section class="download_pdf">
    <div class="container">
        <div class="row">
            <form>
                <div class="col-sm-4">
                    <div class="title">
                        <h2>Download <br>Free PDF Today!</h2>
                    </div>
                </div>
                <div class="col-sm-5">
                    <label>Email*</label>
                    <input type="email" id="txtemailother" class="input_text">
                    <div id="dvWarnMsgother" style="display:none;color:red;font-size:16px;"><b>Please enter valid email id!</b></div>
                </div>
                <div class="col-sm-3">
                    <input type="button" class="submitone" onclick="checkEmailother()" value="Download Now">
                </div>
            </form>
        </div>
    </div>
</section>
<div class="thanks_data_modal">
    <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"></button>
                </div>
                <div class="modal-body">
                    <img src="~/Content/Landing/images/thankyou.png" class="img-responsive" alt="Thank You" />
                    <div class="modal_text">
                        <p>Your whitepaper is being sent to your email. </p>
                        <p>If you would like to learn more about RecordLinc please call us at </p>
                        <a class="clsPhone" href="tel:8005960133">(800)596-0133</a>
                        <span>If you would like to try out a risk free 30 day FREE trial of RecordLinc please hit submit</span>
                        <button class="LandingSubmit" id="btnPageOne" style="width:50% !important;text-align:center;" value="Submit">Submit</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    function checkEmail() {
        
        var emailAddress = $('#txtemail').val();

        if (!isValidEmailAddress(emailAddress)) {

            $('#dvWarnMsg').show();
            $('#txtemail').focus();

        } else {
            $('#dvWarnMsg').hide();
            CallDownloadPdf(emailAddress);                        
        }
    }

    function checkEmailother() {
        
        var emailAddress = $('#txtemailother').val();

        if (!isValidEmailAddress(emailAddress)) {

            $('#dvWarnMsgother').show();
            $('#txtemailother').focus();

        } else {
            $('#dvWarnMsgother').hide();
            CallDownloadPdf(emailAddress);
        }
    }

    function isValidEmailAddress(emailAddress) {
        var pattern = new RegExp(/^[+a-zA-Z0-9._-]+@@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/i);
        return pattern.test(emailAddress);
    }

    function CallDownloadPdf(emailAddress) {
        $.post("/Landing/SendLandingEmail", { emailId: emailAddress, pdfType: 2 }, function (data) {
            if (data != null && data != "") {
                $('#myModal').modal('show');
                $("#txtemailother").val('');
                $("#txtemail").val('');
                $("#btnPageOne").attr("onclick", 'SignUpUser("' + emailAddress + '")');
            }
            else {
                $('#myModal').modal('hide');
            }
        });
    }
    function SignUpUser(email) {
        
        $.post("/Landing/SignupFromLanding", { email: email }, function (data) {
            if (data != null && data != "") {
                
                if (data == "1")
                {
                    swal({ title: "Thank You!", text: 'Your sign-up has been successful. We have sent you activation email on your registered email address. Click on activation link from email to start using RecordLinc.', type: 'success' }, function () {
                        location.href = "@Url.Action("Index", "Login")";
                    });
                }
                if (data == "2")
                {
                    swal({ title: "Thank You!", text: 'You are already registered as a user in Recordlinc. We have resent you activation email on your registered email address. Click on activation link from email to start using RecordLinc.', type: 'success' }, function () {
                        location.href = "@Url.Action("Index", "Login")";
                    });
                }
                if (data == "3")
                {
                    swal({ title: "Thank You!", text: 'You are deactivated by the System Administrator. We have sent you email on your registered email address to activate your account.', type: 'error' }, function () {
                        location.href = "@Url.Action("Index", "Login")";
                    });
                }
                if (data == "4")
                {
                    swal({ title: "Thank You!", text: 'You are already registered as an active user in Recordlinc. We have sent you email with the credentials.', type: 'success' }, function () {
                        location.href = "@Url.Action("Index", "Login")";
                    });
                }
            }
            else {
                swal({ title: "", text: 'Your free trial process is not completed. Please try again.', type:'error' });
            }
        });
    }
    
</script>


NewRecordlinc/Views/Landing/LandingPage2.cshtml

@{
    ViewBag.Title = "Referral-Machine-for-Dentists";
    Layout = "~/Views/Landing/_LandingLayout.cshtml";
}

<link href="~/Content/Landing2/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
<link href="~/Content/Landing2/css/style.css" rel="stylesheet" type="text/css" />
<link href="~/Content/Landing2/css/responsive.css" rel="stylesheet" type="text/css" />
<style>
    .submitone {
        font-family: 'WorkSansRegular';
        font-size: 18px;
        color: #fff;
        background-color: #0e274d;
        border: 0px;
        border-radius: 3px;
        margin-top: 25px;
        padding: 13px 15px;
    }
</style>
<section class="banner">
    <div class="col-sm-3 banner_left">
        <div class="email_download">
            <h1>The Dental referral machine</h1>
            <form>
                <label>Email*</label>  
                <input type="email" id="txtemail" placeholder="Enter your e-mail to download" class="input_text">
                <div id="dvWarnMsg" style="display:none;color:red;font-size:16px;"><b>Please enter valid email id!</b></div>
                <a href="javascript:;" class="banner_btn" onclick="checkEmail()" @*data-toggle="modal"*@ @*data-target="#myModal"*@>Download Now</a>                
            </form>
        </div>
    </div>
    <div class="col-sm-9 banner_right">
        <div class="dentist_guide">
            <div class="title">
                <h2>5 ways to boost your dental practice's patient referrals</h2>
            </div>
            <img src="~/Content/Landing/images/banner_mail.png" class="img-responsive" alt="RecordLinc Mail" />
        </div>
    </div>
</section>
<section class="boost_practice">
    <div class="container">
        <p>
            Word-of-mouth advertising—when one person recommends a product or service to another—ranks at the top of the list of marketing strategies in terms of cost effectiveness. It costs very little yet delivers excellent results. This would explain why dentists give it such high marks. In an April 2015 survey, the Levin Group Data Center™ found 88.3 percent of respondents
            identified “referrals from current patients” as their most successful marketing method.
        </p>
        <p>In the new dental economy, when the number of adult dental care visits is declining, you need to make sure you and your team are doing everything possible to encourage patient referrals.</p>
    </div>
</section>
<section class="best_ways">
    <div class="container">
        <div class="row">
            <div class="col-sm-5 pull-right">
                <img src="~/Content/Landing/images/online_referrals.png" class="img-responsive" alt="Online Referrals" />
            </div>
            <div class="col-sm-7 pull-left">
                <div class="title">
                    <h2>The 6 Best Ways To Get More Patient Referrals Online</h2>
                </div>
                <p>Using your website to get more patients for your practice is an often underutilized method of marketing by many in the healthcare industry. It is time to start taking a focused and strategic approach to the audience you’re trying to attract online to then eventually covert them into long-term patients offline.</p>
                <p>According to TeleVox, 51% of people say they’d feel more valued as a patient through digital health communications. This means that it is time to strengthen your relationships with potential patients online to ensure that awareness of your practice is reaching the most amount of relevant people as possible.</p>
                <ol>
                    <li>Pay Per Click Advertising</li>
                    <li>Search Engine Optimization</li>
                    <li>A Healthcare Database and Booking Service</li>
                    <li>Content Marketing</li>
                    <li>Social Media</li>
                    <li>Email Marketing</li>
                </ol>
            </div>
        </div>
    </div>
</section>
<section class="download_pdf">
    <div class="container">
        <div class="row">
            <form>
                <div class="col-sm-4">
                    <div class="title">
                        <h2>Download <br>Free PDF Today!</h2>
                    </div>
                </div>
                <div class="col-sm-5">
                    <label>Email*</label>
                    <input type="email" id="txtemailother" class="input_text">
                    <div id="dvWarnMsgother" style="display:none;color:red;font-size:16px;"><b>Please enter valid email id!</b></div>
                </div>
                <div class="col-sm-3">
                    <input type="button" class="submitone" onclick="checkEmailother()" value="Download Now">
                </div>
            </form>
        </div>
    </div>
</section>
<div class="thanks_data_modal">
    <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"></button>
                </div>
                <div class="modal-body">
                    <img src="~/Content/Landing/images/thankyou.png" class="img-responsive" alt="Thank You" />
                    <div class="modal_text">
                        <p>Your whitepaper is being sent to your email. </p>
                        <p>If you would like to learn more about RecordLinc please call us at </p>
                        <a class="clsPhone" href="tel:8005960133">(800)596-0133</a>
                        <span>If you would like to try out a risk free 30 day FREE trial of RecordLinc please hit submit</span>
                        <button class="LandingSubmit" id="btnPageTwo" style="width:50% !important;text-align:center;" value="Submit">Submit</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">

    function checkEmail() {
        var emailAddress = $('#txtemail').val();

        if (!isValidEmailAddress(emailAddress)) {

            $('#dvWarnMsg').show();
            $('#txtemail').focus();

        } else {
            $('#dvWarnMsg').hide();
            CallDownloadPdf(emailAddress);            
        }
    }

    function checkEmailother() {
        var emailAddress = $('#txtemailother').val();

        if (!isValidEmailAddress(emailAddress)) {

            $('#dvWarnMsgother').show();
            $('#txtemailother').focus();

        } else {
            $('#dvWarnMsgother').hide();
            CallDownloadPdf(emailAddress);                      
        }
    }

    function isValidEmailAddress(emailAddress) {
        var pattern = new RegExp(/^[+a-zA-Z0-9._-]+@@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/i);
        return pattern.test(emailAddress);
    }
    function CallDownloadPdf(emailAddress) {
        $.post("/Landing/SendLandingEmail", { emailId: emailAddress, pdfType: 3 }, function (data) {
            if (data != null && data != "") {
                $('#myModal').modal('show');
                $("#txtemailother").val('');
                $("#txtemail").val('');
                $("#btnPageTwo").attr("onclick", 'SignUpUser("' + emailAddress + '")');
            }
            else {
                $('#myModal').modal('hide');
            }
        });
    }

    function SignUpUser(email) {
        
        $.post("/Landing/SignupFromLanding", { email: email }, function (data) {
            if (data != null && data != "") {                
                if (data == "1")
                {
                    swal({ title: "Thank You!", text: 'Your sign-up has been successful. We have sent you activation email on your registered email address. Click on activation link from email to start using RecordLinc.', type: 'success' }, function () {
                        location.href = "@Url.Action("Index", "Login")";
                    });
                }
                if (data == "2")
                {
                    swal({ title: "Thank You!", text: 'You are already registered as a user in Recordlinc. We have resent you activation email on your registered email address. Click on activation link from email to start using RecordLinc.', type: 'success' }, function () {
                        location.href = "@Url.Action("Index", "Login")";
                    });
                }
                if (data == "3")
                {
                    swal({ title: "Thank You!", text: 'You are deactivated by the System Administrator. We have sent you email on your registered email address to activate your account.', type: 'error' }, function () {
                        location.href = "@Url.Action("Index", "Login")";
                    });
                }
                if (data == "4")
                {
                    swal({ title: "Thank You!", text: 'You are already registered as an active user in Recordlinc. We have sent you email with the credentials.', type: 'success' }, function () {
                        location.href = "@Url.Action("Index", "Login")";
                    });
                }                
            }
            else {
                swal({ title: "", text: 'Your free trial process is not completed. Please try again.', type:'error' });
            }
        });
    }
</script>